version: 2
updates:
  # For GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  # For Python dependencies
  - package-ecosystem: "pip"
    directory: "/.github"
    schedule:
      interval: "weekly"
