name: JSON Linter
on:
  push:
    paths:
      - '**.json'
    branches:
      - main
  pull_request:
    paths:
      - '**.json'
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt
      - name: Run linter
        run: python .github/scripts/validate_json.py .
