name: MAC
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mac.yaml'
      - 'l10n/webext_l10n.py'
      - 'l10n/exceptions/mac.json'
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          path: "scripts_repo"
      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          repository: "mozilla-l10n/multi-account-containers-l10n"
          path: "target_repo"
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Lint localization
        # Allow to continue if the linter fails, so we can upload the list of
        # errors as artifact
        continue-on-error: true
        run: |
          python scripts_repo/l10n/webext_l10n.py --l10n target_repo/ --ref en --dest errors.txt --exceptions scripts_repo/l10n/exceptions/mac.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: errors-list
          path: errors.txt
          if-no-files-found: ignore
      - name: Fail on errors
        run: |
          if [ -f "errors.txt" ]; then
            cat errors.txt
            exit 1
          fi
