name: Monitor
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/monitor.yaml'
      - '.github/requirements.txt'
      - 'l10n/fluent_l10n.py'
      - 'l10n/exceptions/monitor.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/monitor.yaml'
      - '.github/requirements.txt'
      - 'l10n/fluent_l10n.py'
      - 'l10n/exceptions/monitor.json'
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          path: "scripts_repo"
      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          repository: "mozilla/blurts-server"
          ref: "localization"
          path: "target_repo"
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install -r scripts_repo/.github/requirements.txt
      - name: Lint localization
        run: >
          python scripts_repo/l10n/fluent_l10n.py
          --l10n target_repo/locales/
          --ref en
          --dest errors.txt
          --exceptions scripts_repo/l10n/exceptions/monitor.json
          --no-failure
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: errors-list
          path: errors.txt
          if-no-files-found: ignore
      - name: Fail on errors
        run: |
          if [ -f "errors.txt" ]; then
            cat errors.txt
            exit 1
          fi
