name: Monitor
on:
  schedule:
    - cron: '0 7 * * 1-5' # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          repository: "mozilla/blurts-server"
          ref: "localization"
          path: "target"
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt
      - name: Check strings
        run: |
          python l10n/lint_localization.py --l10n ../target/locales/ --ref en
