name: MozOrg
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mozorg.yaml'
      - 'l10n/fluent_l10n.py'
      - 'l10n/exceptions/mozorg.json'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          path: "scripts_repo"
      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          repository: "mozilla-l10n/www-l10n"
          path: "target_repo"
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          pip install -r scripts_repo/.github/requirements.txt
      - name: Lint localization (vendor)
        # Allow to continue if the linter fails, so we can upload the list of
        # errors as artifact
        continue-on-error: true
        run: >
          python scripts_repo/l10n/fluent_l10n.py
          --toml target_repo/l10n-vendor.toml
          --ref en
          --dest errors_vendors.txt
          --exceptions scripts_repo/l10n/exceptions/mozorg.json
      - name: Lint localization (community)
        continue-on-error: true
        run: >
          python scripts_repo/l10n/fluent_l10n.py
          --toml target_repo/l10n-pontoon.toml
          --ref en
          --dest errors_community.txt
          --exceptions scripts_repo/l10n/exceptions/mozorg.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: errors-list
          path: errors_*.txt
          if-no-files-found: ignore
      - name: Fail on errors
        run: |
          cat errors_vendors.txt || echo "No vendor errors"
          cat errors_community.txt || echo "No community errors"
          if [ -f "errors_vendors.txt" ] || [ -f "errors_community.txt" ]; then
            exit 1
          fi
